# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
