# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170317_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.CharField(default='No label', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(default='No Label'),
        ),
    ]
