# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170320_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='label',
        ),
        migrations.AddField(
            model_name='label',
            name='label_title',
            field=models.CharField(default='work', max_length=20),
            preserve_default=False,
        ),
    ]
