# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20170321_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
