# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20170322_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='description',
        ),
    ]
