# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20170410_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='text',
        ),
    ]
