# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20170410_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(help_text='Enter the description of todo'),
        ),
    ]
