# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20170410_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_title',
            field=models.CharField(help_text='Enter a Todo label(e.g.Work,Groceries etc.)', max_length=20, unique=True),
        ),
    ]
