# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_label_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='owner',
        ),
    ]
